server:
  port: 8080


spring:
  application:
    name: api-gateway

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}